### ISSUE TITLE
[BUG] Build fails on build_webui.py script with FileNotFoundError

### ISSUE THREAD

**Issue by Scrath1** [dewenni/ESP32-Jarolift-Controller#11]
### Is this bug present in the latest release?
- [x] I am using the **latest release**.
- [ ] I am not using the latest release (please update and retest before reporting the bug).

### Hardware Information
- Using generic ESP32-WROOM-32 board. This should be irrelevant for this issue though.

### Bug Description
After downloading the repository and opening it in platformio, the compilation fails on the `build_webui.py` script (Log provided under additional information). The expected behavior would be a successful build.

**Steps to reproduce:**
1. Download the repository and unzip it.
2. Open the repository in platformio and let it configure the project based on the platformio.ini
3. Try to build the project

**Solution:**
The script tries to create a file `web/temp/index.html`.
This operation fails because when the project is downloaded the temp folder does not exist and as such the `index.html` file cannot be created.

A temporary fix is to manually create an empty `temp` folder in the `web` folder. A proper solution to this issue would be to create this folder if necessary using the python script or to add a .gitkeep file to the temp folder so it is included in the repository and already there when the project is downloaded.

### Additional Information
Build log:
```
 *  Executing task: C:\Users\tobia\.platformio\penv\Scripts\platformio.exe run --environment esp32 

Processing esp32 (platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip; board: upesy_wroom; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
FileNotFoundError: [Errno 2] No such file or directory: 'web/temp/index.html':
  File "C:\Users\tobia\.platformio\penv\Lib\site-packages\platformio\builder\main.py", line 167:
    env.SConscript(env.GetExtraScripts("pre"), exports="env")
  File "C:\Users\tobia\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Script\SConscript.py", line 620:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\tobia\.platformio\packages\tool-scons\scons-local-4.8.1\SCons\Script\SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "D:\000_Home\Downloads\ESP32-Jarolift-Controller-main\ESP32-Jarolift-Controller-main\scripts\build_webui.py", line 87:
    with open(output_file_html, 'w') as file:
============================================================================================== [FAILED] Took 1.31 seconds ==============================================================================================
 *  The terminal process "C:\Users\tobia\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'esp32'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by dewenni** [comment]
@Scrath1 thanks for the hint!

you can add this at the beginning of the script and I will add it within the next release.

```python
def ensure_directory_exists(path):
    if not os.path.exists(path):
        os.makedirs(path)
        print(f"folder '{path}' was created.")

# check if temp folder exists, otherwise create it
ensure_directory_exists("web/temp") 
```
