### ISSUE TITLE
[BUG] Modul verlässt setup mode nicht / Wifi setup nicht erfolgreich

### ISSUE THREAD

**Issue by flushbug** [dewenni/ESP32-Jarolift-Controller#2]
### Wurde der Fehler in der neuesten Version getestet?
- [x] Ich nutze die v1.0.0

### Hardware-Informationen
- ESP32-WROOM-32 + CC1101

### Fehlerbeschreibung
- Ich habe die Software auf ein ESP32-WROOM-32 geflasht. Zugriff über Wifi im Setup Mode funktioniert.
- Nachdem ich die Daten meines Wifi Netzes eingegeben habe und neu starte, verbindet sich das Modul zu 98% allerdings
  nicht mit meinem Wifi sondern öffnet weiterhin den Setup Mode (Zugriff über ESP32 AP mode und 192.168.4.1)
- Ich konnte genau ein einziges mal (nicht reproduzierbar) eine Verbindung zu meinem AP herstellen und über die Webseite zugreifen. Nachdem das Modul von der Spannung getrennt wurde landet es zuverlässig nur im Setup Mode.

Gibt es irgendwelche Tricks ? Tastendrücke etc. um das Modul aus dem Setup Mode zu bekommen ? Wifi Signal etc. sollte
kein Problem sein, der AP ist höchstens 1,5 Meter entfernt.

**Comment by dewenni** [comment]
Hi,

danke fürs Testen und Feedback. Ich habe das gerade nochmal bei mir durchgespielt mit einer neuen Inbetriebnahme und konnte das so leider nicht nachstellen.
Mir sind aber noch ein paar Kleinigkeiten dabei aufgefallen die ich in einem neuen [Release v1.1.0](https://github.com/dewenni/ESP32-Jarolift-Controller/releases/tag/v1.1.0) geändert habe.

Generell geht der ESP in den Setup Mode wenn man ihn innerhalb von 3 Sekunden zweimal neu startet.
Das kann man z.B. durch zweimaliges Drücken (innerhalb 3 Sekunden) des Reset-Taster am ESP erreichen.
Das kann aber auch passieren wenn der ESP zyklisch neu startet. Gründe dafür können sehr unterschiedlich sein.
Da wäre es hilfreich wenn man ihn per Kabel am PC anschließt und mittels Serial Monitor von platformIO schaut was da passiert.

- Kannst du die neue Version bitte nochmal testen und Feedback geben?
- nutzt du platformIO oder hast du das fertige image aufgespielt?
- Schau bitte mal im Logger im WebUI was dort eingetragen wird (auch im Fall wenn er in den Setup-Mode geht)
- Oder wenn du den ESP per Kabel angeschlossen hast, im Serial Monitor von platformio

**Comment by flushbug** [comment]
Ich habe jetzt die neue Version geflasht. Dabei direkt das .bin File aus dem Release Ordner genommen.
Über die Console sehe ich dass er den Access Point verbindet aber danach ein Reset ausgelöst wird.
Daraufhin startet er wieder im setup mode.

```
E (146890) wifi:NAN WiFi stop
ets Jul 29 2019 12:21:46
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4832
load:0x40078000,len:16460
load:0x40080400,len:4
load:0x40080404,len:3504
entry 0x400805cc
I (APP-WDT): enable cmd
I (APP-WDT): Watchdog timer initialized for Loop Task
I (APP-SETUP): WiFi Mode STA - Trying connect to: XXXXXXX
I (APP-JARO): initializing the CC1101 Transceiver
D (APP-JARO): set base serial: 0x000000
I (APP-SETUP): Connected to AP successfully!
I (APP-SETUP): WiFi connected
I (APP-SETUP): IP address: 192.168.2.200
E (20607) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
E (20607) task_wdt:  - loopTask (CPU 1)
E (20607) task_wdt: Tasks currently running:
E (20607) task_wdt: CPU 0: IDLE0
E (20607) task_wdt: CPU 1: IDLE1
E (20607) task_wdt: Aborting.
E (20607) task_wdt: Print CPU 1 backtrace
Backtrace: 0x4000bfed:0x3ffbce20 0x40090eec:0x3ffbce30 0x401037ad:0x3ffbce50 0x401037bf:0x3ffbce90 0x4010462e:0x3ffbceb0 0x4008f323:0x3ffbced0 0x40090c6e:0x3ffbcef0
ELF file SHA256: ede4615a669c7c45
Rebooting...
ets Jul 29 2019 12:21:46
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4832
load:0x40078000,len:16460
load:0x40080400,len:4
load:0x40080404,len:3504
entry 0x400805cc
I (APP-SETUP): 
! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
I (APP-SETUP): > WiFi Mode: AccessPoint <
I (APP-SETUP): 1. connect your device to SSID: ESP32-Jarolift
I (APP-SETUP): 2. open Browser and go to Address: http://192.168.4.1
I (APP-SETUP): 
! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
I (APP-TELNET): Telnet Server running!
```

**Comment by dewenni** [comment]
Ok, da geht wohl was mit der Initialisierung des CC1101 schief und dann schlägt der Watchdog zu.

Kurz zur Erklärung:
Wenn das CC1101 Modul nicht korrekt angeschlossen oder konfiguriert ist, dann kann es bei der Initialisierung zu einer Dauerschleife kommen. Das ist leider in dem Treiber von dem Modul so implementiert.
Ich habe daher extra noch eine Überprüfung eingebaut wo ich eine Zustand von dem CC1101 abfrage und die Initialisierung nur dann fortsetze wenn ich eine Antwort vom Modul bekomme. Ich fürchte das dies nicht zuverlässig funktioniert.

Ich habe die Abfrage nochmal angepasst. Es wäre gut wenn du das Image im Anhang nochmal testen könntest.
Wenn das Modul nicht erreichbar ist, solltest du folgendes im Logger sehen:

```
E (APP-JARO): Initialisation of the CC1101 module aborted!
E (APP-JARO): CC1101 Transceiver NOT connected!
```

dann funktioniert das Modul logischerweise auch nicht, aber es sollte dann auch keinen watchdog mehr auslösen.

[Archive.zip](https://github.com/user-attachments/files/18171118/Archive.zip)
(zip entpacken)

**Comment by flushbug** [comment]
Mit der neue Version komme ich stabil in den normalen Modus. Modul wird erkannt usw. Sehr toll, danke !
Könnte jetzt natürlich auch einfach an einem wackeligen HW Setup gelegen haben. Die neue Abfrage ist aber sicherlich
eine gute Verbesserung.

Nun konnte ich erfolgreich Rolladen von einer bestehenden Jarolift Fernbedienung "kopieren" (auf+ab -> 8x Stop -> anlernen) was im Log auch korrekt als angelernt angezeigt wird. Bei der Ansteuerung passiert leider nichts außer den Log Einträgen.
Würde mich aber nicht wundern wenn es hier noch Probleme im HW setup gibt, ich löte das mal vernünftig zusammen.
Fliegender Aufbau ist sicherlich nicht gut für stabile Kommunikation mit dem CC1101 Modul.

Falls es danach nicht weiter geht würde ich aber ein neues Issue starten. Außer du hast hierbei auch noch wertvolle Tips.

**Comment by dewenni** [comment]
freut mich das es funktioniert!
Ich mache dann jetzt noch ein Release mit der geänderten Abfrage.

drücke doch gerne noch den "Stern" - denke das hilft anderen das Projekt zu finden :-)
