### ISSUE TITLE
[FEATURE] HASS: Aktuellen Zustand verstecken

### ISSUE THREAD

**Issue by steffenf02** [dewenni/ESP32-Jarolift-Controller#8]
Moin,

erstmal danke für deine Arbeit, funktioniert größtenteils echt gut, tolles UI, nur hatte ich zwei Probleme: 
- Befehle kommen bei Rolläden nicht immer an
- In Home Assistant wird der aktuelle Zustand angezeigt, wodurch ich keine Befehle doppelt senden kann

Problem 1 wird vermutlich mit einer taktischen Umpositionierung des Senders behoben, aber Problem 2 fällt allerdings auch besonders auf, wenn man die Originalfernbedienung trotzdem weiter nutzen möchte. Oder wenn man z.B. in HASS nach unten drückt, dann stopp drückt, während die Rollade nach unten fährt, dann kann man nicht mehr nach unten weiterfahren, da der "aktuelle Zustand" jetzt unten ist, was den Knopf zum herunterfahren ausgraut.
Hier einfach als Bild:
![image](https://github.com/user-attachments/assets/030879b7-dc26-467c-985c-2d9c6dcbc5ba)

Mit ein paar Änderungen die ich per MQTT Explorer gepfuscht hab, sieht es nun so aus:
![image](https://github.com/user-attachments/assets/9d1eb412-6a56-466b-aa2c-2526d6d0da2d)
![image](https://github.com/user-attachments/assets/0f2c5849-6050-4696-ab37-9dcd6f805ba4)

Wäre super, wenn man den aktuellen Zustand damit also verstecken könnte, damit man immer jeden Befehl senden kann.

Viele Grüße

**Comment by dewenni** [comment]
@steffenf02 
Ich habe das im aktuellen Release v1.3.0 geändert.
Home Assistant ignoriert nun generell den Status und es ist nun möglich auch mehrfach das gleiche Kommando auszuführen. Teste es gerne mal aus und gib mir Feedback.
Außerdem habe ich die Gruppenfunktion implementiert.

**Comment by flushbug** [comment]
Funktioniert bestens.
